# Generated by Django 2.1.5 on 2022-10-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_controller',
            name='password',
        ),
    ]
