# Generated by Django 2.1.5 on 2022-10-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_remove_user_controller_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_controller',
            old_name='sex',
            new_name='gender',
        ),
    ]
