# Generated by Django 2.1.5 on 2022-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_auto_20221008_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_controller',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
