# Generated by Django 4.1.2 on 2022-10-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0011_user_controller_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_controller',
            name='image',
        ),
    ]
